BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CRS_DAY_SCHEDULE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CRS_DAY_SCHEDULE does not exist. Skipping drop...');
END;
/
CREATE TABLE CRS_DAY_SCHEDULE (
    sch_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
    day_of_week VARCHAR2(10) NOT NULL,
    is_week_end CHAR(1)      NOT NULL,
    CONSTRAINT pk_crs_day_schedule PRIMARY KEY (sch_id),
    CONSTRAINT uq_crs_day_schedule UNIQUE (day_of_week),
    CONSTRAINT ck_crs_day_weekend CHECK (is_week_end IN ('Y','N'))
);
