BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CRS_TRAIN_SCHEDULE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CRS_TRAIN_SCHEDULE does not exist. Skipping drop...');
END;
/
CREATE TABLE CRS_TRAIN_SCHEDULE (
    tsch_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    sch_id        NUMBER NOT NULL,
    train_id      NUMBER NOT NULL,
    is_in_service CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT pk_crs_train_schedule PRIMARY KEY (tsch_id),
    CONSTRAINT uq_crs_train_schedule UNIQUE (train_id, sch_id),
    CONSTRAINT fk_crs_ts_sch FOREIGN KEY (sch_id)
        REFERENCES CRS_DAY_SCHEDULE (sch_id),
    CONSTRAINT fk_crs_ts_train FOREIGN KEY (train_id)
        REFERENCES CRS_TRAIN_INFO (train_id),
    CONSTRAINT ck_crs_ts_service CHECK (is_in_service IN ('Y','N'))
);
