SET SERVEROUTPUT ON;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CRS_RESERVATION CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CRS_RESERVATION does not exist. Skipping drop...');
END;
/
CREATE TABLE CRS_RESERVATION (
    booking_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
    passenger_id      NUMBER       NOT NULL,
    train_id          NUMBER       NOT NULL,
    travel_date       DATE         NOT NULL,
    booking_date      DATE         DEFAULT SYSDATE NOT NULL,
    seat_class        VARCHAR2(5)  NOT NULL,
    seat_status       VARCHAR2(12) NOT NULL,
    waitlist_position NUMBER(3),
    CONSTRAINT pk_crs_reservation PRIMARY KEY (booking_id),
    CONSTRAINT fk_crs_res_passenger FOREIGN KEY (passenger_id)
        REFERENCES CRS_PASSENGER (passenger_id),
    CONSTRAINT fk_crs_res_train FOREIGN KEY (train_id)
        REFERENCES CRS_TRAIN_INFO (train_id),
    CONSTRAINT ck_crs_res_seat_class CHECK (seat_class IN ('FC','ECON')),
    CONSTRAINT ck_crs_res_status CHECK (seat_status IN ('CONFIRMED','WAITLISTED','CANCELLED')),
    CONSTRAINT ck_crs_res_waitlist CHECK (waitlist_position IS NULL OR waitlist_position > 0)
);
