BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CRS_TRAIN_INFO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CRS_TRAIN_INFO does not exist. Skipping drop...');
END;
/
CREATE TABLE CRS_TRAIN_INFO (
    train_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
    train_number     VARCHAR2(20) NOT NULL,
    source_station   VARCHAR2(50) NOT NULL,
    dest_station     VARCHAR2(50) NOT NULL,
    total_fc_seats   NUMBER(3)    NOT NULL,
    total_econ_seats NUMBER(3)    NOT NULL,
    fc_seat_fare     NUMBER(8,2)  NOT NULL,
    econ_seat_fare   NUMBER(8,2)  NOT NULL,
    CONSTRAINT pk_crs_train_info PRIMARY KEY (train_id),
    CONSTRAINT uq_crs_train_number UNIQUE (train_number),
    CONSTRAINT ck_fc_seats CHECK (total_fc_seats >= 0),
    CONSTRAINT ck_econ_seats CHECK (total_econ_seats >= 0),
    CONSTRAINT ck_fc_fare CHECK (fc_seat_fare >= 0),
    CONSTRAINT ck_econ_fare CHECK (econ_seat_fare >= 0)
);
