BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE CRS_PASSENGER CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CRS_PASSENGER does not exist. Skipping drop...');
END;
/
CREATE TABLE CRS_PASSENGER (
    passenger_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    first_name     VARCHAR2(50)  NOT NULL,
    middle_name    VARCHAR2(50),
    last_name      VARCHAR2(50)  NOT NULL,
    date_of_birth  DATE          NOT NULL,
    address_line1  VARCHAR2(100) NOT NULL,
    address_city   VARCHAR2(50)  NOT NULL,
    address_state  VARCHAR2(50)  NOT NULL,
    address_zip    VARCHAR2(10)  NOT NULL,
    email          VARCHAR2(100) NOT NULL,
    phone          VARCHAR2(20)  NOT NULL,
    CONSTRAINT pk_crs_passenger PRIMARY KEY (passenger_id),
    CONSTRAINT uq_crs_passenger_email UNIQUE (email),
    CONSTRAINT uq_crs_passenger_phone UNIQUE (phone)
);
