
CREATE ROLE CRS_APP_ROLE;

GRANT CREATE SESSION TO CRS_APP_ROLE;


CREATE USER CRS_ADMIN IDENTIFIED BY Password#123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION TO CRS_ADMIN;

GRANT CREATE TABLE,
      CREATE VIEW,
      CREATE SEQUENCE,
      CREATE PROCEDURE,
      CREATE TRIGGER,
      CREATE SYNONYM
TO CRS_ADMIN;

CREATE USER CRS_APP IDENTIFIED BY Password#123
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA UNLIMITED ON USERS;

GRANT CRS_APP_ROLE TO CRS_APP;


GRANT CREATE SYNONYM TO CRS_APP;
