BEGIN
EXECUTE IMMEDIATE 'DROP TABLE CRS_DAY_SCHEDULE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CRS_DAY_SCHEDULE does not exist. Skipping drop...');
END;
/
CREATE TABLE CRS_DAY_SCHEDULE (
                                  sch_id      NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                  day_of_week VARCHAR2(10) NOT NULL,
                                  is_week_end CHAR(1)      NOT NULL,
                                  CONSTRAINT pk_crs_day_schedule PRIMARY KEY (sch_id),
                                  CONSTRAINT uq_crs_day_schedule UNIQUE (day_of_week),
                                  CONSTRAINT ck_crs_day_weekend CHECK (is_week_end IN ('Y','N'))
);
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE CRS_PASSENGER CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CRS_PASSENGER does not exist. Skipping drop...');
END;
/
CREATE TABLE CRS_PASSENGER (
                               passenger_id   NUMBER GENERATED BY DEFAULT AS IDENTITY,
                               first_name     VARCHAR2(50)  NOT NULL,
                               middle_name    VARCHAR2(50),
                               last_name      VARCHAR2(50)  NOT NULL,
                               date_of_birth  DATE          NOT NULL,
                               address_line1  VARCHAR2(100) NOT NULL,
                               address_city   VARCHAR2(50)  NOT NULL,
                               address_state  VARCHAR2(50)  NOT NULL,
                               address_zip    VARCHAR2(10)  NOT NULL,
                               email          VARCHAR2(100) NOT NULL,
                               phone          VARCHAR2(20)  NOT NULL,
                               CONSTRAINT pk_crs_passenger PRIMARY KEY (passenger_id),
                               CONSTRAINT uq_crs_passenger_email UNIQUE (email),
                               CONSTRAINT uq_crs_passenger_phone UNIQUE (phone)
);
SET SERVEROUTPUT ON;

BEGIN
EXECUTE IMMEDIATE 'DROP TABLE CRS_RESERVATION CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CRS_RESERVATION does not exist. Skipping drop...');
END;
/
CREATE TABLE CRS_RESERVATION (
                                 booking_id        NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                 passenger_id      NUMBER       NOT NULL,
                                 train_id          NUMBER       NOT NULL,
                                 travel_date       DATE         NOT NULL,
                                 booking_date      DATE         DEFAULT SYSDATE NOT NULL,
                                 seat_class        VARCHAR2(5)  NOT NULL,
                                 seat_status       VARCHAR2(12) NOT NULL,
                                 waitlist_position NUMBER(3),
                                 CONSTRAINT pk_crs_reservation PRIMARY KEY (booking_id),
                                 CONSTRAINT fk_crs_res_passenger FOREIGN KEY (passenger_id)
                                     REFERENCES CRS_PASSENGER (passenger_id),
                                 CONSTRAINT fk_crs_res_train FOREIGN KEY (train_id)
                                     REFERENCES CRS_TRAIN_INFO (train_id),
                                 CONSTRAINT ck_crs_res_seat_class CHECK (seat_class IN ('FC','ECON')),
                                 CONSTRAINT ck_crs_res_status CHECK (seat_status IN ('CONFIRMED','WAITLISTED','CANCELLED')),
                                 CONSTRAINT ck_crs_res_waitlist CHECK (waitlist_position IS NULL OR waitlist_position > 0)
);
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE CRS_TRAIN_INFO CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CRS_TRAIN_INFO does not exist. Skipping drop...');
END;
/
CREATE TABLE CRS_TRAIN_INFO (
                                train_id         NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                train_number     VARCHAR2(20) NOT NULL,
                                source_station   VARCHAR2(50) NOT NULL,
                                dest_station     VARCHAR2(50) NOT NULL,
                                total_fc_seats   NUMBER(3)    NOT NULL,
                                total_econ_seats NUMBER(3)    NOT NULL,
                                fc_seat_fare     NUMBER(8,2)  NOT NULL,
                                econ_seat_fare   NUMBER(8,2)  NOT NULL,
                                CONSTRAINT pk_crs_train_info PRIMARY KEY (train_id),
                                CONSTRAINT uq_crs_train_number UNIQUE (train_number),
                                CONSTRAINT ck_fc_seats CHECK (total_fc_seats >= 0),
                                CONSTRAINT ck_econ_seats CHECK (total_econ_seats >= 0),
                                CONSTRAINT ck_fc_fare CHECK (fc_seat_fare >= 0),
                                CONSTRAINT ck_econ_fare CHECK (econ_seat_fare >= 0)
);
BEGIN
EXECUTE IMMEDIATE 'DROP TABLE CRS_TRAIN_SCHEDULE CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('CRS_TRAIN_SCHEDULE does not exist. Skipping drop...');
END;
/
CREATE TABLE CRS_TRAIN_SCHEDULE (
                                    tsch_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
                                    sch_id        NUMBER NOT NULL,
                                    train_id      NUMBER NOT NULL,
                                    is_in_service CHAR(1) DEFAULT 'Y' NOT NULL,
                                    CONSTRAINT pk_crs_train_schedule PRIMARY KEY (tsch_id),
                                    CONSTRAINT uq_crs_train_schedule UNIQUE (train_id, sch_id),
                                    CONSTRAINT fk_crs_ts_sch FOREIGN KEY (sch_id)
                                        REFERENCES CRS_DAY_SCHEDULE (sch_id),
                                    CONSTRAINT fk_crs_ts_train FOREIGN KEY (train_id)
                                        REFERENCES CRS_TRAIN_INFO (train_id),
                                    CONSTRAINT ck_crs_ts_service CHECK (is_in_service IN ('Y','N'))
);