SET SERVEROUTPUT ON;

BEGIN
    -- Grant EXECUTE on packages
EXECUTE IMMEDIATE 'GRANT EXECUTE ON PKG_CRS_PASSENGER   TO CRS_APP_ROLE';
DBMS_OUTPUT.PUT_LINE('Granted EXECUTE on PKG_CRS_PASSENGER to CRS_APP_ROLE.');

EXECUTE IMMEDIATE 'GRANT EXECUTE ON PKG_CRS_RESERVATION TO CRS_APP_ROLE';
DBMS_OUTPUT.PUT_LINE('Granted EXECUTE on PKG_CRS_RESERVATION to CRS_APP_ROLE.');

    -- Grant SELECT on tables
EXECUTE IMMEDIATE 'GRANT SELECT ON CRS_TRAIN_INFO      TO CRS_APP_ROLE';
DBMS_OUTPUT.PUT_LINE('Granted SELECT on CRS_TRAIN_INFO to CRS_APP_ROLE.');

EXECUTE IMMEDIATE 'GRANT SELECT ON CRS_DAY_SCHEDULE    TO CRS_APP_ROLE';
DBMS_OUTPUT.PUT_LINE('Granted SELECT on CRS_DAY_SCHEDULE to CRS_APP_ROLE.');

EXECUTE IMMEDIATE 'GRANT SELECT ON CRS_TRAIN_SCHEDULE  TO CRS_APP_ROLE';
DBMS_OUTPUT.PUT_LINE('Granted SELECT on CRS_TRAIN_SCHEDULE to CRS_APP_ROLE.');

EXECUTE IMMEDIATE 'GRANT SELECT ON CRS_PASSENGER       TO CRS_APP_ROLE';
DBMS_OUTPUT.PUT_LINE('Granted SELECT on CRS_PASSENGER to CRS_APP_ROLE.');

EXECUTE IMMEDIATE 'GRANT SELECT ON CRS_RESERVATION     TO CRS_APP_ROLE';
DBMS_OUTPUT.PUT_LINE('Granted SELECT on CRS_RESERVATION to CRS_APP_ROLE.');

    -- Grant INSERT, UPDATE on tables
EXECUTE IMMEDIATE 'GRANT INSERT, UPDATE ON CRS_PASSENGER   TO CRS_APP_ROLE';
DBMS_OUTPUT.PUT_LINE('Granted INSERT, UPDATE on CRS_PASSENGER to CRS_APP_ROLE.');

EXECUTE IMMEDIATE 'GRANT INSERT, UPDATE ON CRS_RESERVATION TO CRS_APP_ROLE';
DBMS_OUTPUT.PUT_LINE('Granted INSERT, UPDATE on CRS_RESERVATION to CRS_APP_ROLE.');
END;
/
COMMIT;