SET SERVEROUTPUT ON;

------------------------------------------------------------
-- GRANT ALL PRIVILEGES TO CRS_APP
------------------------------------------------------------
DECLARE
v_dummy NUMBER;
BEGIN
    -- Table Grants
EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON CRS_ADMIN.CRS_DAY_SCHEDULE TO CRS_APP';
DBMS_OUTPUT.PUT_LINE('Granted CRUD on CRS_DAY_SCHEDULE to CRS_APP');

EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON CRS_ADMIN.CRS_TRAIN_INFO TO CRS_APP';
DBMS_OUTPUT.PUT_LINE('Granted CRUD on CRS_TRAIN_INFO to CRS_APP');

EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON CRS_ADMIN.CRS_TRAIN_SCHEDULE TO CRS_APP';
DBMS_OUTPUT.PUT_LINE('Granted CRUD on CRS_TRAIN_SCHEDULE to CRS_APP');

EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON CRS_ADMIN.CRS_PASSENGER TO CRS_APP';
DBMS_OUTPUT.PUT_LINE('Granted CRUD on CRS_PASSENGER to CRS_APP');

EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE, DELETE ON CRS_ADMIN.CRS_RESERVATION TO CRS_APP';
DBMS_OUTPUT.PUT_LINE('Granted CRUD on CRS_RESERVATION to CRS_APP');

    -- Sequence Grants
EXECUTE IMMEDIATE 'GRANT SELECT ON CRS_ADMIN.CRS_DAY_SCHEDULE_SEQ_PK TO CRS_APP';
DBMS_OUTPUT.PUT_LINE('Granted SELECT on CRS_DAY_SCHEDULE_SEQ_PK');

EXECUTE IMMEDIATE 'GRANT SELECT ON CRS_ADMIN.CRS_TRAIN_INFO_SEQ_PK TO CRS_APP';
DBMS_OUTPUT.PUT_LINE('Granted SELECT on CRS_TRAIN_INFO_SEQ_PK');

EXECUTE IMMEDIATE 'GRANT SELECT ON CRS_ADMIN.CRS_TRAIN_SCHEDULE_SEQ_PK TO CRS_APP';
DBMS_OUTPUT.PUT_LINE('Granted SELECT on CRS_TRAIN_SCHEDULE_SEQ_PK');

EXECUTE IMMEDIATE 'GRANT SELECT ON CRS_ADMIN.CRS_PASSENGER_SEQ_PK TO CRS_APP';
DBMS_OUTPUT.PUT_LINE('Granted SELECT on CRS_PASSENGER_SEQ_PK');

EXECUTE IMMEDIATE 'GRANT SELECT ON CRS_ADMIN.CRS_RESERVATION_SEQ_PK TO CRS_APP';
DBMS_OUTPUT.PUT_LINE('Granted SELECT on CRS_RESERVATION_SEQ_PK');

    -- Package Grants
EXECUTE IMMEDIATE 'GRANT EXECUTE ON CRS_ADMIN.PKG_CRS_PASSENGER TO CRS_APP';
DBMS_OUTPUT.PUT_LINE('Granted EXECUTE on PKG_CRS_PASSENGER');

EXECUTE IMMEDIATE 'GRANT EXECUTE ON CRS_ADMIN.PKG_CRS_RESERVATION TO CRS_APP';
DBMS_OUTPUT.PUT_LINE('Granted EXECUTE on PKG_CRS_RESERVATION');
END;
/