SET SERVEROUTPUT ON;

------------------------------------------------------------
-- 1. DROP + CREATE SYNONYMS FOR PACKAGES
------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM PKG_CRS_PASSENGER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM PKG_CRS_PASSENGER FOR CRS_ADMIN.PKG_CRS_PASSENGER;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM PKG_CRS_RESERVATION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM PKG_CRS_RESERVATION FOR CRS_ADMIN.PKG_CRS_RESERVATION;
/

------------------------------------------------------------
-- 2. DROP + CREATE SYNONYMS FOR TABLES
------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_TRAIN_INFO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_TRAIN_INFO FOR CRS_ADMIN.CRS_TRAIN_INFO;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_DAY_SCHEDULE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_DAY_SCHEDULE FOR CRS_ADMIN.CRS_DAY_SCHEDULE;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_TRAIN_SCHEDULE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_TRAIN_SCHEDULE FOR CRS_ADMIN.CRS_TRAIN_SCHEDULE;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_PASSENGER'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_PASSENGER FOR CRS_ADMIN.CRS_PASSENGER;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_RESERVATION'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_RESERVATION FOR CRS_ADMIN.CRS_RESERVATION;
/

------------------------------------------------------------
-- 3. DROP + CREATE SYNONYMS FOR SEQUENCES
------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_TRAIN_INFO_SEQ_PK'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_TRAIN_INFO_SEQ_PK FOR CRS_ADMIN.CRS_TRAIN_INFO_SEQ_PK;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_DAY_SCHEDULE_SEQ_PK'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_DAY_SCHEDULE_SEQ_PK FOR CRS_ADMIN.CRS_DAY_SCHEDULE_SEQ_PK;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_TRAIN_SCHEDULE_SEQ_PK'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_TRAIN_SCHEDULE_SEQ_PK FOR CRS_ADMIN.CRS_TRAIN_SCHEDULE_SEQ_PK;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_PASSENGER_SEQ_PK'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_PASSENGER_SEQ_PK FOR CRS_ADMIN.CRS_PASSENGER_SEQ_PK;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_RESERVATION_SEQ_PK'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_RESERVATION_SEQ_PK FOR CRS_ADMIN.CRS_RESERVATION_SEQ_PK;
/

------------------------------------------------------------
-- 4. DROP + CREATE "_TBL" SYNONYMS (OPTIONAL MAPPING)
------------------------------------------------------------
BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_TRAIN_INFO_TBL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_TRAIN_INFO_TBL FOR CRS_ADMIN.CRS_TRAIN_INFO;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_DAY_SCHEDULE_TBL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_DAY_SCHEDULE_TBL FOR CRS_ADMIN.CRS_DAY_SCHEDULE;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_PASSENGER_TBL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_PASSENGER_TBL FOR CRS_ADMIN.CRS_PASSENGER;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_RESERVATION_TBL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_RESERVATION_TBL FOR CRS_ADMIN.CRS_RESERVATION;
/

BEGIN EXECUTE IMMEDIATE 'DROP SYNONYM CRS_TRAIN_SCHEDULE_TBL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE SYNONYM CRS_TRAIN_SCHEDULE_TBL FOR CRS_ADMIN.CRS_TRAIN_SCHEDULE;
/

------------------------------------------------------------
-- END OF SCRIPT
------------------------------------------------------------
